### ISSUE TITLE
Input matrix is ill-conditioned

### ISSUE THREAD

**Issue by xxchenxx** [microsoft/otdd#12]
Thank you for your notice. 

When I ran `d,out = flow.flow()`
I got:

> RuntimeError: symeig_cpu: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 635).

Is there any solution for this error? Thanks a lot!

**Comment by dmelis** [comment]
Duplicate Issue: https://github.com/microsoft/otdd/issues/4
