### ISSUE TITLE
ImportError: cannot import name 'embedded_feature_cost' from 'otdd.pytorch.distance'

### ISSUE THREAD

**Issue by chengrunyang** [microsoft/otdd#3]
Hi, I get the above error when trying to run the second example in README (first example in Advanced Usage), and I couldn't find where `embedded_feature_cost` is defined. I've followed the installation instructions in a conda virtual environment. Could you help take a look? Thanks!

**Comment by dmelis** [comment]
Thanks. The README example was using the old syntax (via functools.partial). Now FeatureCost is a class, so that isn't needed anymore. Fixed the README and added a python script with the advanced example.
