### ISSUE TITLE
"Unexpected keyword argument" bug in last commit

### ISSUE THREAD

**Issue by addtt** [microsoft/otdd#6]
Hi! The refactoring in the last commit seems to have introduced a small bug where `load_full_dataset()` ([here](https://github.com/microsoft/otdd/blob/9faa6cf64aec3990306843171dda91b1bd2e7ff7/otdd/pytorch/utils.py#L190)) is called with an argument `reindex_start` that does not exist (e.g. [here](https://github.com/microsoft/otdd/blob/9faa6cf64aec3990306843171dda91b1bd2e7ff7/otdd/pytorch/distance.py#L258) and in a couple other places).

I'm not sure, but it might be enough to add `reindex_start=None` to the signature of `load_full_dataset()` and then change [this](https://github.com/microsoft/otdd/blob/9faa6cf64aec3990306843171dda91b1bd2e7ff7/otdd/pytorch/utils.py#L280-L281) into the following:

```python
if type(reindex) is bool:
    if reindex_start is None:
        reindex_start = 0
    reindex_vals = range(reindex_start, reindex_start + len(labels))
```

Does it make sense? Thanks!

**Comment by dmelis** [comment]
Hi, good catch. I forgot to push the latest version of utils.py, which introduced this bug. Should be fixed by the latest push.
